### ISSUE TITLE
Damage roll not working

### ISSUE THREAD

**Issue by CrownBerry** [tonyrobots/dcc-qol#1]
Versions
FoundryVTT: 12.328
DCC system: v0.42.0
DCC-QoL: 0.0.23

Enabled modules:
<img width="677" alt="image" src="https://github.com/tonyrobots/dcc-qol/assets/8062502/87ed70bb-8182-49f0-8d60-e212e7c8ffb7">

Module settings:
<img width="558" alt="image" src="https://github.com/tonyrobots/dcc-qol/assets/8062502/fb934587-7514-40c1-8b78-23ae11b73532">

Description:
I created a simple actor with a longsword and imported a wolf from the compendium. When I attack a wolf with this longsword, the attack roll goes fine, but pressing the "Damage" button does not roll anything.

Also, there is an error in DevTools console:
<img width="1205" alt="image" src="https://github.com/tonyrobots/dcc-qol/assets/8062502/fe4c51a0-d8aa-49a5-a0e5-3d39ea5bcc38">

Error message:
TypeError: Cannot read properties of undefined (reading 'system')
    at DCCActor.rollDamage (actor.js:1137:26)
    at HTMLButtonElement.ChatCardAction (chat.js:80:48)
    at HTMLElement.dispatch (jquery.min.js:2:40035)
    at v.handle (jquery.min.js:2:38006)

**Comment by CrownBerry** [comment]
This works after the server restart.
