### ISSUE TITLE
[BUG] Unable to roll weapon attacks when DCC QoL is enabled under new DCC Game System

### ISSUE THREAD

**Issue by Cerender** [tonyrobots/dcc-qol#4]
**Describe the bug**
Click a Ranged or Melee weapon attack roll on character sheet and nothing happens. Other character sheet rolls work. Saves Checks or Spells

**To Reproduce**
1. Open character sheet
2. Click die icon to roll attack

**Expected behavior**
Clicking die triggers attack roll

**Screenshots**

** Versions **
Foundry version:  12.331
DCC system version: 0.50.8 & 0.50.9
dcc-qol module version:  0.1.27

**Additional context**
foundry.js:3402 Uncaught (in promise) Error: undefined. "dcc.automateUntrainedAttack" is not a registered game setting
[Detected 3 packages: dcc-qol(0.1.27), lib-wrapper(1.13.2.0), system:dcc(0.50.9)]
    at #assertKey (foundry.js:3402:42)
    at ClientSettings.get (foundry.js:3334:26)
    at DCCQOL.rollToHitQOL (patch.js:514:55)
    at DCCQOL.rollWeaponAttackQOL (patch.js:280:45)
    at DCCActor.rollPatchedWeaponAttack (dcc-qol.js:44:11)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:639:16)
    at 🎁game.dcc.DCCActor.prototype.rollWeaponAttack#0 (libWrapper-wrapper.js:193:20)
    at DCCActorSheetWizard._onRollWeaponAttack (actor-sheet.js:792:16)
    at HTMLDivElement.dispatch (jquery.min.js:2:40035)
    at v.handle (jquery.min.js:2:38006)

**Comment by tonyrobots** [comment]
Yes, unfortunately dcc-qol is not compatible with the new DCC system (versions 0.50+). Working on that now!
